namespace Utilities.Enum
{
    //reference to https://ctrlq.org/code/19899-google-translate-languages as of 11/08/2019
    public static class Language
    {
        public const string Afrikaans = "af";
        public const string Albanian = "sq";
        public const string Arabic = "ar";
        public const string Azerbaijani = "az";
        public const string Basque = "eu";
        public const string Bengali = "bn";
        public const string Belarusian = "be";
        public const string Bulgarian = "bg";
        public const string Catalan = "ca";
        public const string Chinese_Simplified = "zh-CN";
        public const string Chinese_Traditional = "zh-TW";
        public const string Croatian = "hr";
        public const string Czech = "cs";
        public const string Danish = "da";
        public const string Dutch = "nl";
        public const string English = "en";
        public const string Esperanto = "eo";
        public const string Estonian = "et";
        public const string Filipino = "tl";
        public const string Finnish = "fi";
        public const string French = "fr";
        public const string Galician = "gl";
        public const string Georgian = "ka";
        public const string German = "de";
        public const string Greek = "el";
        public const string Gujarati = "gu";
        public const string Haitian_Creole = "ht";
        public const string Hebrew = "iw";
        public const string Hindi = "hi";
        public const string Hungarian = "hu";
        public const string Icelandic = "is";
        public const string Indonesian = "id";
        public const string Irish = "ga";
        public const string Italian = "it";
        public const string Japanese = "ja";
        public const string Kannada = "kn";
        public const string Korean = "ko";
        public const string Latin = "la";
        public const string Latvian = "lv";
        public const string Lithuanian = "lt";
        public const string Macedonian = "mk";
        public const string Malay = "ms";
        public const string Maltese = "mt";
        public const string Norwegian = "no";
        public const string Persian = "fa";
        public const string Polish = "pl";
        public const string Portuguese = "pt";
        public const string Romanian = "ro";
        public const string Russian = "ru";
        public const string Serbian = "sr";
        public const string Slovak = "sk";
        public const string Slovenian = "sl";
        public const string Spanish = "es";
        public const string Swahili = "sw";
        public const string Swedish = "sv";
        public const string Tamil = "ta";
        public const string Telugu = "te";
        public const string Thai = "th";
        public const string Turkish = "tr";
        public const string Ukrainian = "uk";
        public const string Urdu = "ur";
        public const string Vietnamese = "vi";
        public const string Welsh = "cy";
        public const string Yiddish = "yi";
    }
}